@baseurl = http://localhost:5075

GET  {{baseurl}}/games

###
GET  {{baseurl}}/games/3

###
 POST {{baseurl}}/games
 Content-Type: application/json

{
  "name": "MineCreaft",
  "genre": "Kids and family",
  "price": 59.99,
  "releaseDate": "2024-02-24T00:00:00"
}

###
 PUT {{baseurl}}/games/1
 Content-Type: application/json

{
  "name": "MineCreaft1",
  "genre": "Kids and family",
  "price": 59.99,
  "releaseDate": "2024-02-24T00:00:00"
}

###
 DELETE  {{baseurl}}/games/1
 
